---
title: "Pokemon visualizations!"
author: "Joshua Megnauth"
date: "August 11, 2020"
output:
  html_document:
    theme: darkly
    highlight: zenburn
    df_print: paged
---
I found this awesome data set [on Kaggle](https://www.kaggle.com/rounakbanik/pokemon)!

## Pokémon!

```{r libraries_n_loading, warning=FALSE, message=FALSE}
library(kableExtra)
library(broom)
library(tidyverse)
library(ggplot2)

pokemon <- read_csv("Pokemon_data.csv")

# MEGA ULTRA CLEANING WOW.

pokemon <-
  pokemon %>%
  rename(category = classfication) %>%
  mutate(pokedex_number = as.integer(pokedex_number),
         generation = as_factor(generation),
         category = as_factor(category),
         abilities = str_remove_all(abilities, "\\[|'|\\]"),
         type1 = as_factor(type1),
         type2 = as_factor(na_if(type2, "None")),
         is_legendary = as_factor(is_legendary),
         is_mythical = as_factor(is_mythical),
         is_mega = as_factor(is_mega)) %>%
  separate(abilities, c("abilities_one", "abilities_two", "abilities_three"),
           sep = ", ") %>%
  gather("drop_me", "abilities", matches("abilities_*")) %>%
  mutate(abilities = as_factor(abilities)) %>%
  select(-drop_me) %>%
  arrange(pokedex_number)

head(pokemon)
```

I worked on a binary classifier for [predicting graduate school admissions](https://joshuamegnauth54.github.io/docs/projects/data/science/admissions2.html) as my first project. 

Notes to self: Decide if variables like against_*, capture_rate et cetera should be turned into nominals.
```{r test_graphs}
pokemon %>%
  ggplot(aes(base_total)) +
  geom_histogram()
```
